Five new APIs to facilitate docbot Development
tosdr/API pull request #17
Opened 2023-12-30 21:33 UTC by radkoff

Document GET, Point GET/POST, and DocbotRecords GET/POST

Testing done: new Appwrite functions were set up in staging, and I was able to hit each one with curl. Confirmed that new Points/DocbotRecords are in the staging DB

OpenAPI docs aren't working right yet but I still added yaml files for the new APIs

2024-02-20 22:39 UTC, JustinBack requested changes

2024-02-20 22:39 UTC, JustinBack commented on appwrite.json
> +            "path": "functions/internal/Point/GET/v1",
Move from internal to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/README.md
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/gruntfile.js
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/package-lock.json
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/package.json
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/src/helpers/Phoenix.ts
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/src/index.ts
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/GET/v1/tsconfig.json
Move to public

2024-02-20 22:39 UTC, JustinBack commented on functions/internal/Point/spec/point.yaml
Move GET to public

2024-08-26 20:26 UTC, radkoff commented
Fixed a bug that was preventing POST content from being read in the bridge. Testing done: ran the bridge locally via Docker, using env variables to point to prod appwrite. Tested both new POSTs, and a GET to make sure that didn't break

2024-09-07 04:13 UTC, merged